/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package D_Repaso.A_Lavavajillas;

/**
 * Esta ventana muestra el panel de opciones de un lavavajillas virtual<br>
 * Podremos pulsar los botones para abrir/cerrar la puerta<br>
 * Podremos pulsar los botones para encender/apagar el lavavajillas<br>
 * Podremos cambiar de programa (enjuagado, prelavado, lavado, aclarado, secado)<br>
 * Podremos avanzar de programa automaticamente
 * @author Ignacio
 */
public class VentanaLavavajillas extends javax.swing.JFrame {

    /**
     * Objeto de tipo Lavavajillas
     */
    private Lavavajillas lavavajillas;
    
    /**
     * Constructor de la Ventana, por orden:<br>
     *   Se inicializan los componentes<br>
     *   Se centra la ventana<br>
     *   Se reserva memoria para el objeto lavavajillas<br>
     *   Mostramos el estado inicial del lavavajillas
     */
    public VentanaLavavajillas() {
        initComponents();
        
        //Centramos la ventana
        setLocationRelativeTo(null);
        
        //Declaramos el objeto lavavajillas
        lavavajillas = new Lavavajillas();
        
        //Establecemos el estado por defecto
        mostrarEstado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBAbrir = new javax.swing.JButton();
        jBCerrar = new javax.swing.JButton();
        jBEncender = new javax.swing.JButton();
        jBApagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTFEstadoPuerta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFEstadoEnergia = new javax.swing.JTextField();
        jBEnjuagado = new javax.swing.JButton();
        jBPrelavado = new javax.swing.JButton();
        jBLavado = new javax.swing.JButton();
        jBAclarado = new javax.swing.JButton();
        jBSecado = new javax.swing.JButton();
        jBAvanzarEstado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTFEstadoPrograma = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lavavajillas");

        jBAbrir.setText("Abrir Puerta");
        jBAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAbrirActionPerformed(evt);
            }
        });

        jBCerrar.setText("Cerrar Puerta");
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });

        jBEncender.setText("Encender");
        jBEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEncenderActionPerformed(evt);
            }
        });

        jBApagar.setText("Apagar");
        jBApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBApagarActionPerformed(evt);
            }
        });

        jLabel1.setText("Puerta:");

        jLabel2.setText("Energía:");

        jBEnjuagado.setText("Enjuagado");
        jBEnjuagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnjuagadoActionPerformed(evt);
            }
        });

        jBPrelavado.setText("Prelavado");
        jBPrelavado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPrelavadoActionPerformed(evt);
            }
        });

        jBLavado.setText("Lavado");
        jBLavado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLavadoActionPerformed(evt);
            }
        });

        jBAclarado.setText("Aclarado");
        jBAclarado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAclaradoActionPerformed(evt);
            }
        });

        jBSecado.setText("Secado");
        jBSecado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSecadoActionPerformed(evt);
            }
        });

        jBAvanzarEstado.setText("Avanzar estado automáticamente");
        jBAvanzarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAvanzarEstadoActionPerformed(evt);
            }
        });

        jLabel3.setText("Programa:");

        jTFEstadoPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEstadoProgramaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBAbrir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBCerrar)
                                .addGap(18, 18, 18)
                                .addComponent(jBEncender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBApagar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFEstadoPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFEstadoEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBEnjuagado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBPrelavado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBLavado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBAclarado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBSecado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBAvanzarEstado)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFEstadoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAbrir)
                    .addComponent(jBCerrar)
                    .addComponent(jBEncender)
                    .addComponent(jBApagar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFEstadoPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTFEstadoEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEnjuagado)
                    .addComponent(jBPrelavado)
                    .addComponent(jBLavado)
                    .addComponent(jBAclarado)
                    .addComponent(jBSecado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAvanzarEstado)
                    .addComponent(jLabel3)
                    .addComponent(jTFEstadoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAbrirActionPerformed
        lavavajillas.setAbierto(true);
        mostrarEstado();
    }//GEN-LAST:event_jBAbrirActionPerformed

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        lavavajillas.setAbierto(false);
        mostrarEstado();
    }//GEN-LAST:event_jBCerrarActionPerformed

    private void jBEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEncenderActionPerformed
        lavavajillas.setEncendido(true);
        mostrarEstado();
    }//GEN-LAST:event_jBEncenderActionPerformed

    private void jBApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBApagarActionPerformed
        lavavajillas.setEncendido(false);
        mostrarEstado();        
    }//GEN-LAST:event_jBApagarActionPerformed

    private void jBEnjuagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnjuagadoActionPerformed
        lavavajillas.setPrograma(Lavavajillas.ENJUAGADO);
        mostrarEstado();
    }//GEN-LAST:event_jBEnjuagadoActionPerformed

    private void jBPrelavadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPrelavadoActionPerformed
        lavavajillas.setPrograma(Lavavajillas.PRELAVADO);
        mostrarEstado();
    }//GEN-LAST:event_jBPrelavadoActionPerformed

    private void jBLavadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLavadoActionPerformed
        lavavajillas.setPrograma(Lavavajillas.LAVADO);
        mostrarEstado();
    }//GEN-LAST:event_jBLavadoActionPerformed

    private void jBAclaradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAclaradoActionPerformed
        lavavajillas.setPrograma(Lavavajillas.ACLARADO);
        mostrarEstado();
    }//GEN-LAST:event_jBAclaradoActionPerformed

    private void jBSecadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSecadoActionPerformed
        lavavajillas.setPrograma(Lavavajillas.SECADO);
        mostrarEstado();
    }//GEN-LAST:event_jBSecadoActionPerformed

    private void jTFEstadoProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEstadoProgramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEstadoProgramaActionPerformed

    private void jBAvanzarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAvanzarEstadoActionPerformed
        lavavajillas.avanzarPrograma();
        mostrarEstado();
    }//GEN-LAST:event_jBAvanzarEstadoActionPerformed

    /**
     * Muestra el estado en el que se encuentra el lavavajillas<br>
     * Actualiza los textos que aparecen en los TextFields
     */
    public void mostrarEstado(){
         jTFEstadoPuerta.setText(lavavajillas.getAbierto());
         jTFEstadoEnergia.setText(lavavajillas.getEncendido());
         jTFEstadoPrograma.setText(lavavajillas.getPrograma());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLavavajillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLavavajillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLavavajillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLavavajillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLavavajillas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAbrir;
    private javax.swing.JButton jBAclarado;
    private javax.swing.JButton jBApagar;
    private javax.swing.JButton jBAvanzarEstado;
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jBEncender;
    private javax.swing.JButton jBEnjuagado;
    private javax.swing.JButton jBLavado;
    private javax.swing.JButton jBPrelavado;
    private javax.swing.JButton jBSecado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTFEstadoEnergia;
    private javax.swing.JTextField jTFEstadoPrograma;
    private javax.swing.JTextField jTFEstadoPuerta;
    // End of variables declaration//GEN-END:variables
}
